function [  ] = SPM_align(person_id)
%-----------------------------------------------------------------------
% Job saved on 21-Jul-2022 14:58:27 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
%%
clear jobs;
jobs{1}.spm.spatial.realign.estwrite.data = {
                                                    {
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_1.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_10.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_100.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_101.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_102.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_103.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_104.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_105.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_106.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_107.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_108.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_109.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_11.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_110.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_111.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_112.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_113.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_114.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_115.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_116.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_117.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_118.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_119.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_12.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_120.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_121.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_122.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_123.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_124.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_125.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_126.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_127.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_128.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_129.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_13.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_130.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_131.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_132.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_133.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_134.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_135.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_136.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_137.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_138.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_139.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_14.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_140.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_141.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_142.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_143.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_144.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_145.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_146.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_147.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_148.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_149.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_15.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_150.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_151.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_152.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_153.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_154.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_155.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_156.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_157.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_158.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_159.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_16.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_160.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_17.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_18.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_19.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_2.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_20.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_21.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_22.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_23.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_24.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_25.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_26.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_27.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_28.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_29.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_3.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_30.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_31.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_32.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_33.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_34.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_35.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_36.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_37.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_38.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_39.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_4.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_40.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_41.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_42.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_43.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_44.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_45.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_46.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_47.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_48.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_49.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_5.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_50.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_51.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_52.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_53.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_54.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_55.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_56.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_57.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_58.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_59.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_6.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_60.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_61.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_62.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_63.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_64.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_65.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_66.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_67.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_68.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_69.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_7.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_70.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_71.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_72.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_73.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_74.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_75.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_76.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_77.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_78.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_79.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_8.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_80.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_81.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_82.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_83.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_84.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_85.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_86.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_87.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_88.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_89.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_9.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_90.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_91.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_92.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_93.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_94.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_95.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_96.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_97.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_98.nii,1']
                                                    ['E:\DCE_Model_Selection\' person_id '\dynamic_series\dyn_99.nii,1']
                                                    }
                                                    }';
%%
jobs{1}.spm.spatial.realign.estwrite.eoptions.quality = 0.9;
jobs{1}.spm.spatial.realign.estwrite.eoptions.sep = 4;
jobs{1}.spm.spatial.realign.estwrite.eoptions.fwhm = 5;
jobs{1}.spm.spatial.realign.estwrite.eoptions.rtm = 1;
jobs{1}.spm.spatial.realign.estwrite.eoptions.interp = 2;
jobs{1}.spm.spatial.realign.estwrite.eoptions.wrap = [0 0 0];
jobs{1}.spm.spatial.realign.estwrite.eoptions.weight = '';
jobs{1}.spm.spatial.realign.estwrite.roptions.which = [2 1];
jobs{1}.spm.spatial.realign.estwrite.roptions.interp = 4;
jobs{1}.spm.spatial.realign.estwrite.roptions.wrap = [0 0 0];
jobs{1}.spm.spatial.realign.estwrite.roptions.mask = 1;
jobs{1}.spm.spatial.realign.estwrite.roptions.prefix = 'r';

spm('Defaults','pet');
spm_jobman('initcfg');
spm_jobman('run',jobs);
% oplist = spm_jobman('run',jobs);
spm quit;
end